--[[
This module is licensed under the GNU General Public License v3.0 (GPLv3).
Copyright (C) 2025 NoahIsADeveloper

You are free to use, modify, and redistribute this code under the terms of
the GPLv3 license.

This code is provided **WITHOUT ANY WARRANTY** — not even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should have received a copy of the full license with this project.
If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

Source repository: https://github.com/NoahIsADeveloper/Slate
]]